In [10]:
import pandas as pd
df = pd.read_csv("./yf/prediction_201808_sorted.csv")
df.head()

,price,postcode,paon,saon,predicted_price,logerror,abslogerror
0,335000.0,SM5 1HS,365,NaN,334999,1.862433e-07,1.862433e-07
1,148750.0,CV2 3BU,38,NaN,148750,-1.530639e-06,1.530639e-06
2,445000.0,ME14 2EQ,15,NaN,444993,1.424928e-05,1.424928e-05
3,325000.0,TN10 3HS,1,NaN,325011,-3.595462e-05,3.595462e-05
4,91000.0,CW8 1BP,WEAVER VIEW FLATS,4,90996,4.014604e-05,4.014604e-05